spring.application.name=fs-orders
#DB
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=${DDL_AUTO:none}
server.port=${SERVER_PORT:8083}
spring.data.web.pageable.serialization-mode=via-dto
#public key
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=${AUTH_PUBLIC_JWT_URL:http://auth-service:8081/api/internal/auth/.well-known/jwks.json}
#Stripe
stripe.api-key=${STRIPE_API_KEY}
stripe.success-url=${STRIPE_SUCCESS_URL}
stripe.cancel-url=${STRIPE_CANCEL_URL}
#Services
product-service-url=${PRODUCT_SERVICE_URL}
inventory-service-url=${INVENTORY_SERVICE_URL}
cart-service-url=${CART_SERVICE_URL}
#AWS
spring.cloud.aws.region.static=eu-north-1
app.queues.order-paid-events=${ORDER_PAID_SQS}
app.queues.confirm-reservation=${CONFIRM_RESERVATION_SQS}
