spring.application.name=fake-store-orderservice
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=${DDL_AUTO:none}
spring.jpa.show-sql=true
server.port=${SERVER_PORT:8083}
spring.data.web.pageable.serialization-mode=via-dto
spring.security.oauth2.resourceserver.jwt.public-key-data=${JWT_PUBLIC_KEY}
#Stripe
stripe.api-key=${STRIPE_API_KEY}
stripe.success-url=${STRIPE_SUCCESS_URL}
stripe.cancel-url=${STRIPE_CANCEL_URL}
stripe.webhook-secret=${STRIPE_WEBHOOK_SECRET}
#Services
product-service-url=${PRODUCT_SERVICE_URL}
