spring.security.oauth2.resourceserver.jwt.jwk-set-uri=${AUTH_PUBLIC_JWT_URL:http://auth-service:8081/api/internal/auth/.well-known/jwks.json}
# Stripe
stripe.api-key=
stripe.success-url=
stripe.cancel-url=
# Internal urls
product-service-url=
inventory-service-url=
#MESSAGING
spring.rabbitmq.addresses=${RABBITMQ_URL}

