spring.config.import=aws-parameterstore:/config/orders/
spring.datasource.url=
spring.datasource.username=
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=${DDL_AUTO:none}
server.port=${SERVER_PORT:8083}
spring.data.web.pageable.serialization-mode=via-dto
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=${AUTH_PUBLIC_JWT_URL:http://auth-service:8081/api/internal/auth/.well-known/jwks.json}
# Stripe
stripe.api-key=
stripe.success-url=
stripe.cancel-url=
# Internal urls
product-service-url=
inventory-service-url=
spring.cloud.aws.region.static=${AWS_STATIC_REGION:eu-north-1}
# Aws sqs
app.queues.order-paid-events=${ORDER_PAID_SQS}
app.queues.confirm-reservation=${CONFIRM_RESERVATION_SQS}
